=== eclypsium/dfb/you_shall_not_parse/you_shall_not_parse/schemas/pylint_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "type": { "type": "string" },
            "module": { "type": "string" },
            "obj": { "type": "string" },
            "line": { "type": "integer" },
            "column": { "type": "integer" },
            "endLine": { "type": ["integer", "null"] },
            "endColumn": { "type": ["integer", "null"] },
            "path": { "type": "string" },
            "symbol": { "type": "string" },
            "message": { "type": "string" },
            "message-id": { "type": "string" }
        },
        "required": ["type", "module", "obj", "line", "column", "path", "symbol", "message", "message-id"],
        "additionalProperties": false
    }
}

=== eclypsium/dfb/you_shall_not_parse/examples/pylint-abram.json
[
    {
        "type": "convention",
        "module": "abram.abram_base_types",
        "obj": "",
        "line": 1,
        "column": 0,
        "endLine": null,
        "endColumn": null,
        "path": "abram/abram_base_types.py",
        "symbol": "missing-module-docstring",
        "message": "Missing module docstring",
        "message-id": "C0114"
    },
    {
        "type": "convention",
        "module": "abram.abram_collection",
        "obj": "",
        "line": 1,
        "column": 0,
        "endLine": null,
        "endColumn": null,
        "path": "abram/abram_collection.py",
        "symbol": "missing-module-docstring",
        "message": "Missing module docstring",
        "message-id": "C0114"
    },
    {
        "type": "convention",
        "module": "abram.abram_collection",
        "obj": "Collection.intersection",
        "line": 24,
        "column": 4,
        "endLine": 24,
        "endColumn": 20,
        "path": "abram/abram_collection.py",
        "symbol": "missing-function-docstring",
        "message": "Missing function or method docstring",
        "message-id": "C0116"
    },
    {
        "type": "warning",
        "module": "abram.abram_collection",
        "obj": "Collection.intersection",
        "line": 26,
        "column": 19,
        "endLine": 26,
        "endColumn": 44,
        "path": "abram/abram_collection.py",
        "symbol": "protected-access",
        "message": "Access to a protected member _iterate_collection of a client class",
        "message-id": "W0212"
    }
]

=== eclypsium/dfb/you_shall_not_parse/examples/pylint.json
[
    {
        "type": "error",
        "module": "abram.abram_engine",
        "obj": "",
        "line": 21,
        "column": 0,
        "endLine": 21,
        "endColumn": 48,
        "path": "abram/abram_engine.py",
        "symbol": "import-error",
        "message": "Unable to import 'abram_preprocessor.main'",
        "message-id": "E0401"
    },
    {
        "type": "error",
        "module": "abram.abram_engine",
        "obj": "",
        "line": 22,
        "column": 0,
        "endLine": 22,
        "endColumn": 46,
        "path": "abram/abram_engine.py",
        "symbol": "import-error",
        "message": "Unable to import 'cdt_lib_engine.evaluator'",
        "message-id": "E0401"
    },
    {
        "type": "refactor",
        "module": "abram.abram_engine",
        "obj": "ABRAMExtension",
        "line": 68,
        "column": 0,
        "endLine": 68,
        "endColumn": 20,
        "path": "abram/abram_engine.py",
        "symbol": "too-few-public-methods",
        "message": "Too few public methods (1/2)",
        "message-id": "R0903"
    }
]
